### ISSUE TITLE
Camera not working.

### ISSUE THREAD

**Issue by m16a172** [manjaro-pinephone/phosh-dev#1]
Opening the Megapixels app gives a camera preview, and switching between the front and rear camera works. When you try to take a picture, the app freezes momentarily then closes. No picture is taken. Otherwise, this is an encouraging OS for PinePhone.

**Comment by hphilm** [comment]
Known issue due to newer kernels. **Megapixels** is more a demo app. See [here](https://todo.sr.ht/~martijnbraam/Megapixels) for upstream issues.

**Comment by hphilm** [comment]
Fixed via 1.0.1 version of **megapixels**
