### ISSUE TITLE
uboot update broke my install

### ISSUE THREAD

**Issue by ghost** [manjaro-pinephone/phosh-dev#11]
Just updated uboot and now I am stucked in the red led light after trying to reboot

**Comment by hphilm** [comment]
**uboot-pinephone 2021.07-4** fixes it. Reflash the image and update again.

**Comment by hphilm** [comment]
More info here: https://gitlab.manjaro.org/manjaro-arm/packages/core/uboot-pinephone/-/merge_requests/3#note_23979
