### ISSUE TITLE
No login to root -- 20220209 img below

### ISSUE THREAD

**Issue by tckosvic** [manjaro-pinephone/phosh-dev#15]
Downloaded and installed phosh-manjaro 20220201 img below to SD  Inserted to pinephonepro. All loaded fine including setup.  Except can't login to root from terminal.  Wish to run pacman updates but need root.

tried in terminal:

  su -----> root  (as pw and sure caps wasn't on) says invalid
  
  su ----->  123456  (as pw and also says invalid

I will try an earlier version

**Comment by tckosvic** [comment]
"su"  or "su -" continues to not start root and work.  Found a workaround.  Enter "sudo [then a command like pacman]".   Upon a return will ask for the manjaro (user) login pw.  The numerical pw will then execute the root command.  Seems weird as to why user can run root commands and you can't login to root to run root commands.
I have arch linux (manjaro parent) in a vm on pc and I can su to root on that.

**Comment by hphilm** [comment]
Not a bug, a feature: https://gitlab.manjaro.org/manjaro-arm/packages/community/pinephone-post-install/-/commit/704547cb8d10e5b340e49127272dba06f6a3cb70

**Comment by tckosvic** [comment]
The ref "https://wiki.pine64.org/wiki/PinePhone_Pro_Software_Releases#Manjaro_ARM"  shows root/root login for manjaro
