### ISSUE TITLE
PPP keyboard doesn't work with this os

### ISSUE THREAD

**Issue by jsarkari** [manjaro-pinephone/phosh-dev#21]
The keys don't respond at all using Manjaro Phosh on emmc with towboot installed.

I have been using it ok running arch linux phosh on sd card.

**Comment by jsarkari** [comment]
I have also tested Manjaro Plasma on SD card and the PPP keyboard still doesn't respond. Anything missing as I read Manjaro was one of the supported distros.

**Comment by zen0bit** [comment]
ppkb works for me in mobian and arch. Not in pmos and manjaro not tested yet...

**Comment by Danimations** [comment]
Looking foward to this problem being solved. Very keen to see Pinephone keyboard case support in both Manjaro OS.
