### ISSUE TITLE
Cameras on Pinephone Pro are unsupported

### ISSUE THREAD

**Issue by Danimations** [manjaro-pinephone/phosh-dev#22]
It would be great if devs could propel this forward. I am keen to stick with Manjaro OS on Pinephone Pro after good experiences with it on the regular Pinephone and look forward to camera support being implemented.

**Comment by hphilm** [comment]
It is now supported, however still has poor quality: https://github.com/kgmt0/megapixels/commit/d8b35bc223989cb165ba1b0716ab9f0ca9c43e53
