### ISSUE TITLE
Reboot turns off bluetooth but the icon shows as on after restart

### ISSUE THREAD

**Issue by jsarkari** [manjaro-pinephone/phosh-dev#24]
So I have noticed that after rebooting the mobile usually via terminal (sudo reboot) and I have bluetooth on eg for mouse when in keyboard especially.

Once the PPP has restarted I notice that the bluetooth icon at the top is showing as on, but when I check settings as my mouse isn't responding it is off so I have to keep switching back on.

Is this turned off as part of the shutdown/restart process - if so, I think you need to also check that the icon is switched to showing as off prior to reboot.

Also it would be good to maybe have an option to not have this switched off if you so desire.

**Comment by Popolon** [comment]
I think this problem is resolved now. I seen this on older releases. Could you confirm?
