### ISSUE TITLE
phosh package duplicate call-ui  LC_MESSAGES translation files

### ISSUE THREAD

**Issue by Popolon** [manjaro-pinephone/phosh-dev#32]
The phosh-0.32.0-1 package on repositories duplicate call-ui  LC_MESSAGES translation files from gnome-calls package. This block the upgrade of phosh package (and other package when using -Syu).

<pre>
error: failed to commit transaction (conflicting files)
phosh: /usr/share/locale/ca/LC_MESSAGES/call-ui.mo exists in filesystem (owned by gnome-calls)
phosh: /usr/share/locale/cs/LC_MESSAGES/call-ui.mo exists in filesystem (owned by gnome-calls)
phosh: /usr/share/locale/de/LC_MESSAGES/call-ui.mo exists in filesystem (owned by gnome-calls)
phosh: /usr/share/locale/el/LC_MESSAGES/call-ui.mo exists in filesystem (owned by gnome-calls)
phosh: /usr/share/locale/es/LC_MESSAGES/call-ui.mo exists in filesystem (owned by gnome-calls)
phosh: /usr/share/locale/eu/LC_MESSAGES/call-ui.mo exists in filesystem (owned by gnome-calls)
[…]
</pre>

**Comment by hphilm** [comment]
Arch builds **phosh** with `D callui-i18n=true` enabled. However they don't ship **gnome-calls** yet. So we have to see on how to deal with that. Is it part of **Gnome-Calls** or does **Phosh** also uses translations of **call-ui**.

**Comment by Popolon** [comment]
Looks like only manjaro (arm ?) on pinephone distro was impacted by this bug. It has been patched today, the phosh package now only contains LC_MESSAGES from Phosh
